WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

WINDOW_TITLE = "Elastic collision simulation"
WINDOW_BACKGROUND_COLOR = (255, 255, 255)

GRAVITY_VERTICAL = 0
GRAVITY_HORIZONTAL = 0

ENVIRONMENT_DENSITY = 0.1

MIN_PARTICLE_AMOUNT = 5
MAX_PARTICLE_AMOUNT = 40
